import{a as L,S,i as q}from"./assets/vendor-CtT2CgVQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const E="49711703-11461993d80a106b3cce7e78b",P="https://pixabay.com/api/";let k=15,p=1;async function f(e){try{const r=await L.get(P,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:k,page:p}});return p+=1,{images:r.data.hits,totalHits:r.data.totalHits}}catch(r){return console.error("Error fetching images:",r.message),{images:[],totalHits:0}}}function w(){p=1}const H=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function $(e){return e.map(({webformatURL:r,largeImageURL:o,tags:n,likes:t,views:s,comments:i,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${r}" alt="${n}" loading="lazy" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="tittle">Likes</h2><p class="amount">${t}</p></div>
          <div class="block"><h2 class="tittle">Views</h2><p class="amount">${s}</p></div>
          <div class="block"><h2 class="tittle">Comments</h2><p class="amount">${i}</p></div>
          <div class="block"><h2 class="tittle">Downloads</h2><p class="amount">${v}</p></div>
        </div>
      </li>`).join("")}function g(e){document.querySelector(".gallery").insertAdjacentHTML("beforeend",$(e)),H.refresh(),b()}function a(e){q.error({title:"Error",message:e,position:"topRight"})}function b(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}}const m=document.querySelector(".form"),M=document.querySelector(".input-search"),O=document.querySelector(".gallery"),c=document.querySelector(".loader"),d=document.querySelector(".loader-load"),l=document.querySelector(".btn-load");c.style.display="none";l.style.display="none";d.style.display="none";let u="",h=0,y=0;m.addEventListener("submit",function(e){e.preventDefault();const r=M.value.trim();if(r===""){a("Please enter a search query!");return}w(),O.innerHTML="",l.style.display="none",c.style.display="block",u=r,f(u).then(({images:o,totalHits:n})=>{if(c.style.display="none",o.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}h=n,y=o.length,g(o),y<h?l.style.display="block":(l.style.display="none",a("We're sorry, but you've reached the end of search results."))}).catch(o=>{c.style.display="none",a("Error fetching images. Please try again!"),console.error("Помилка сервера:",o.message)}),m.reset()});l.addEventListener("click",async()=>{u!==""&&(d.style.display="block",l.style.display="none",await f(u).then(({images:e})=>{if(d.style.display="none",e.length===0){a("We're sorry, but you've reached the end of search results.");return}g(e),b(),y+=e.length,y>=h?(l.style.display="none",a("We're sorry, but you've reached the end of search results.")):l.style.display="block"}).catch(e=>{d.style.display="none",a("Error loading more images."),console.error("Помилка сервера:",e.message)}))});
//# sourceMappingURL=index.js.map
